## Tools for working with Licenses.
## 
## The `License` object assumes the use of SPDX identifiers conforming with
## version 3.19 of the SPDX license list.
## 

import types
import std/tables

type LicenseData = tuple[name, id: string, isFsfLibre, isOsiApproved, isDeprecated: bool]

let spdxTbl = block:
  const Licenses: array[500, LicenseData] = [
    ("BSD Zero Clause License", "0BSD", false, true, false),
    ("Attribution Assurance License", "AAL", false, true, false),
    ("Abstyles License", "Abstyles", false, false, false),
    ("Adobe Systems Incorporated Source Code License Agreement", "Adobe-2006", false, false, false),
    ("Adobe Glyph List License", "Adobe-Glyph", false, false, false),
    ("Amazon Digital Services License", "ADSL", false, false, false),
    ("Academic Free License v1.1", "AFL-1.1", true, true, false),
    ("Academic Free License v1.2", "AFL-1.2", true, true, false),
    ("Academic Free License v2.0", "AFL-2.0", true, true, false),
    ("Academic Free License v2.1", "AFL-2.1", true, true, false),
    ("Academic Free License v3.0", "AFL-3.0", true, true, false),
    ("Afmparse License", "Afmparse", false, false, false),
    ("Affero General Public License v1.0 only", "AGPL-1.0-only", false, false, false),
    ("Affero General Public License v1.0 or later", "AGPL-1.0-or-later", false, false, false),
    ("GNU Affero General Public License v3.0 only", "AGPL-3.0-only", true, true, false),
    ("GNU Affero General Public License v3.0 or later", "AGPL-3.0-or-later", true, true, false),
    ("Aladdin Free Public License", "Aladdin", false, false, false),
    ("AMD's plpa_map.c License", "AMDPLPA", false, false, false),
    ("Apple MIT License", "AML", false, false, false),
    ("Academy of Motion Picture Arts and Sciences BSD", "AMPAS", false, false, false),
    ("ANTLR Software Rights Notice", "ANTLR-PD", false, false, false),
    ("ANTLR Software Rights Notice with license fallback", "ANTLR-PD-fallback", false, false, false),
    ("Apache License 1.0", "Apache-1.0", true, false, false),
    ("Apache License 1.1", "Apache-1.1", true, true, false),
    ("Apache License 2.0", "Apache-2.0", true, true, false),
    ("Adobe Postscript AFM License", "APAFML", false, false, false),
    ("Adaptive Public License 1.0", "APL-1.0", false, true, false),
    ("App::s2p License", "App-s2p", false, false, false),
    ("Apple Public Source License 1.0", "APSL-1.0", false, true, false),
    ("Apple Public Source License 1.1", "APSL-1.1", false, true, false),
    ("Apple Public Source License 1.2", "APSL-1.2", false, true, false),
    ("Apple Public Source License 2.0", "APSL-2.0", true, true, false),
    ("Arphic Public License", "Arphic-1999", false, false, false),
    ("Artistic License 1.0", "Artistic-1.0", false, true, false),
    ("Artistic License 1.0 w/clause 8", "Artistic-1.0-cl8", false, true, false),
    ("Artistic License 1.0 (Perl)", "Artistic-1.0-Perl", false, true, false),
    ("Artistic License 2.0", "Artistic-2.0", true, true, false),
    ("Baekmuk License", "Baekmuk", false, false, false),
    ("Bahyph License", "Bahyph", false, false, false),
    ("Barr License", "Barr", false, false, false),
    ("Beerware License", "Beerware", false, false, false),
    ("Bitstream Vera Font License", "Bitstream-Vera", false, false, false),
    ("BitTorrent Open Source License v1.0", "BitTorrent-1.0", false, false, false),
    ("BitTorrent Open Source License v1.1", "BitTorrent-1.1", true, false, false),
    ("SQLite Blessing", "blessing", false, false, false),
    ("Blue Oak Model License 1.0.0", "BlueOak-1.0.0", false, false, false),
    ("Borceux license", "Borceux", false, false, false),
    ("BSD 1-Clause License", "BSD-1-Clause", false, true, false),
    ("BSD 2-Clause \"Simplified\" License", "BSD-2-Clause", true, true, false),
    ("BSD-2-Clause Plus Patent License", "BSD-2-Clause-Patent", false, true, false),
    ("BSD 2-Clause with views sentence", "BSD-2-Clause-Views", false, false, false),
    ("BSD 3-Clause \"New\" or \"Revised\" License", "BSD-3-Clause", true, true, false),
    ("BSD with attribution", "BSD-3-Clause-Attribution", false, false, false),
    ("BSD 3-Clause Clear License", "BSD-3-Clause-Clear", true, false, false),
    ("Lawrence Berkeley National Labs BSD variant license", "BSD-3-Clause-LBNL", false, true, false),
    ("BSD 3-Clause Modification", "BSD-3-Clause-Modification", false, false, false),
    ("BSD 3-Clause No Military License", "BSD-3-Clause-No-Military-License", false, false, false),
    ("BSD 3-Clause No Nuclear License", "BSD-3-Clause-No-Nuclear-License", false, false, false),
    ("BSD 3-Clause No Nuclear License 2014", "BSD-3-Clause-No-Nuclear-License-2014", false, false, false),
    ("BSD 3-Clause No Nuclear Warranty", "BSD-3-Clause-No-Nuclear-Warranty", false, false, false),
    ("BSD 3-Clause Open MPI variant", "BSD-3-Clause-Open-MPI", false, false, false),
    ("BSD 4-Clause \"Original\" or \"Old\" License", "BSD-4-Clause", true, false, false),
    ("BSD 4 Clause Shortened", "BSD-4-Clause-Shortened", false, false, false),
    ("BSD-4-Clause (University of California-Specific)", "BSD-4-Clause-UC", false, false, false),
    ("BSD Protection License", "BSD-Protection", false, false, false),
    ("BSD Source Code Attribution", "BSD-Source-Code", false, false, false),
    ("Boost Software License 1.0", "BSL-1.0", true, true, false),
    ("Business Source License 1.1", "BUSL-1.1", false, false, false),
    ("bzip2 and libbzip2 License v1.0.6", "bzip2-1.0.6", false, false, false),
    ("Computational Use of Data Agreement v1.0", "C-UDA-1.0", false, false, false),
    ("Cryptographic Autonomy License 1.0", "CAL-1.0", false, true, false),
    ("Cryptographic Autonomy License 1.0 (Combined Work Exception)", "CAL-1.0-Combined-Work-Exception", false, true, false),
    ("Caldera License", "Caldera", false, false, false),
    ("Computer Associates Trusted Open Source License 1.1", "CATOSL-1.1", false, true, false),
    ("Creative Commons Attribution 1.0 Generic", "CC-BY-1.0", false, false, false),
    ("Creative Commons Attribution 2.0 Generic", "CC-BY-2.0", false, false, false),
    ("Creative Commons Attribution 2.5 Generic", "CC-BY-2.5", false, false, false),
    ("Creative Commons Attribution 2.5 Australia", "CC-BY-2.5-AU", false, false, false),
    ("Creative Commons Attribution 3.0 Unported", "CC-BY-3.0", false, false, false),
    ("Creative Commons Attribution 3.0 Austria", "CC-BY-3.0-AT", false, false, false),
    ("Creative Commons Attribution 3.0 Germany", "CC-BY-3.0-DE", false, false, false),
    ("Creative Commons Attribution 3.0 IGO", "CC-BY-3.0-IGO", false, false, false),
    ("Creative Commons Attribution 3.0 Netherlands", "CC-BY-3.0-NL", false, false, false),
    ("Creative Commons Attribution 3.0 United States", "CC-BY-3.0-US", false, false, false),
    ("Creative Commons Attribution 4.0 International", "CC-BY-4.0", true, false, false),
    ("Creative Commons Attribution Non Commercial 1.0 Generic", "CC-BY-NC-1.0", false, false, false),
    ("Creative Commons Attribution Non Commercial 2.0 Generic", "CC-BY-NC-2.0", false, false, false),
    ("Creative Commons Attribution Non Commercial 2.5 Generic", "CC-BY-NC-2.5", false, false, false),
    ("Creative Commons Attribution Non Commercial 3.0 Unported", "CC-BY-NC-3.0", false, false, false),
    ("Creative Commons Attribution Non Commercial 3.0 Germany", "CC-BY-NC-3.0-DE", false, false, false),
    ("Creative Commons Attribution Non Commercial 4.0 International", "CC-BY-NC-4.0", false, false, false),
    ("Creative Commons Attribution Non Commercial No Derivatives 1.0 Generic", "CC-BY-NC-ND-1.0", false, false, false),
    ("Creative Commons Attribution Non Commercial No Derivatives 2.0 Generic", "CC-BY-NC-ND-2.0", false, false, false),
    ("Creative Commons Attribution Non Commercial No Derivatives 2.5 Generic", "CC-BY-NC-ND-2.5", false, false, false),
    ("Creative Commons Attribution Non Commercial No Derivatives 3.0 Unported", "CC-BY-NC-ND-3.0", false, false, false),
    ("Creative Commons Attribution Non Commercial No Derivatives 3.0 Germany", "CC-BY-NC-ND-3.0-DE", false, false, false),
    ("Creative Commons Attribution Non Commercial No Derivatives 3.0 IGO", "CC-BY-NC-ND-3.0-IGO", false, false, false),
    ("Creative Commons Attribution Non Commercial No Derivatives 4.0 International", "CC-BY-NC-ND-4.0", false, false, false),
    ("Creative Commons Attribution Non Commercial Share Alike 1.0 Generic", "CC-BY-NC-SA-1.0", false, false, false),
    ("Creative Commons Attribution Non Commercial Share Alike 2.0 Generic", "CC-BY-NC-SA-2.0", false, false, false),
    ("Creative Commons Attribution-NonCommercial-ShareAlike 2.0 France", "CC-BY-NC-SA-2.0-FR", false, false, false),
    ("Creative Commons Attribution Non Commercial Share Alike 2.0 England and Wales", "CC-BY-NC-SA-2.0-UK", false, false, false),
    ("Creative Commons Attribution Non Commercial Share Alike 2.5 Generic", "CC-BY-NC-SA-2.5", false, false, false),
    ("Creative Commons Attribution Non Commercial Share Alike 3.0 Unported", "CC-BY-NC-SA-3.0", false, false, false),
    ("Creative Commons Attribution Non Commercial Share Alike 3.0 Germany", "CC-BY-NC-SA-3.0-DE", false, false, false),
    ("Creative Commons Attribution Non Commercial Share Alike 3.0 IGO", "CC-BY-NC-SA-3.0-IGO", false, false, false),
    ("Creative Commons Attribution Non Commercial Share Alike 4.0 International", "CC-BY-NC-SA-4.0", false, false, false),
    ("Creative Commons Attribution No Derivatives 1.0 Generic", "CC-BY-ND-1.0", false, false, false),
    ("Creative Commons Attribution No Derivatives 2.0 Generic", "CC-BY-ND-2.0", false, false, false),
    ("Creative Commons Attribution No Derivatives 2.5 Generic", "CC-BY-ND-2.5", false, false, false),
    ("Creative Commons Attribution No Derivatives 3.0 Unported", "CC-BY-ND-3.0", false, false, false),
    ("Creative Commons Attribution No Derivatives 3.0 Germany", "CC-BY-ND-3.0-DE", false, false, false),
    ("Creative Commons Attribution No Derivatives 4.0 International", "CC-BY-ND-4.0", false, false, false),
    ("Creative Commons Attribution Share Alike 1.0 Generic", "CC-BY-SA-1.0", false, false, false),
    ("Creative Commons Attribution Share Alike 2.0 Generic", "CC-BY-SA-2.0", false, false, false),
    ("Creative Commons Attribution Share Alike 2.0 England and Wales", "CC-BY-SA-2.0-UK", false, false, false),
    ("Creative Commons Attribution Share Alike 2.1 Japan", "CC-BY-SA-2.1-JP", false, false, false),
    ("Creative Commons Attribution Share Alike 2.5 Generic", "CC-BY-SA-2.5", false, false, false),
    ("Creative Commons Attribution Share Alike 3.0 Unported", "CC-BY-SA-3.0", false, false, false),
    ("Creative Commons Attribution Share Alike 3.0 Austria", "CC-BY-SA-3.0-AT", false, false, false),
    ("Creative Commons Attribution Share Alike 3.0 Germany", "CC-BY-SA-3.0-DE", false, false, false),
    ("Creative Commons Attribution Share Alike 4.0 International", "CC-BY-SA-4.0", true, false, false),
    ("Creative Commons Public Domain Dedication and Certification", "CC-PDDC", false, false, false),
    ("Creative Commons Zero v1.0 Universal", "CC0-1.0", true, false, false),
    ("Common Development and Distribution License 1.0", "CDDL-1.0", true, true, false),
    ("Common Development and Distribution License 1.1", "CDDL-1.1", false, false, false),
    ("Common Documentation License 1.0", "CDL-1.0", false, false, false),
    ("Community Data License Agreement Permissive 1.0", "CDLA-Permissive-1.0", false, false, false),
    ("Community Data License Agreement Permissive 2.0", "CDLA-Permissive-2.0", false, false, false),
    ("Community Data License Agreement Sharing 1.0", "CDLA-Sharing-1.0", false, false, false),
    ("CeCILL Free Software License Agreement v1.0", "CECILL-1.0", false, false, false),
    ("CeCILL Free Software License Agreement v1.1", "CECILL-1.1", false, false, false),
    ("CeCILL Free Software License Agreement v2.0", "CECILL-2.0", true, false, false),
    ("CeCILL Free Software License Agreement v2.1", "CECILL-2.1", false, true, false),
    ("CeCILL-B Free Software License Agreement", "CECILL-B", true, false, false),
    ("CeCILL-C Free Software License Agreement", "CECILL-C", true, false, false),
    ("CERN Open Hardware Licence v1.1", "CERN-OHL-1.1", false, false, false),
    ("CERN Open Hardware Licence v1.2", "CERN-OHL-1.2", false, false, false),
    ("CERN Open Hardware Licence Version 2 - Permissive", "CERN-OHL-P-2.0", false, true, false),
    ("CERN Open Hardware Licence Version 2 - Strongly Reciprocal", "CERN-OHL-S-2.0", false, true, false),
    ("CERN Open Hardware Licence Version 2 - Weakly Reciprocal", "CERN-OHL-W-2.0", false, true, false),
    ("Checkmk License", "checkmk", false, false, false),
    ("Clarified Artistic License", "ClArtistic", true, false, false),
    ("CNRI Jython License", "CNRI-Jython", false, false, false),
    ("CNRI Python License", "CNRI-Python", false, true, false),
    ("CNRI Python Open Source GPL Compatible License Agreement", "CNRI-Python-GPL-Compatible", false, false, false),
    ("Copyfree Open Innovation License", "COIL-1.0", false, false, false),
    ("Community Specification License 1.0", "Community-Spec-1.0", false, false, false),
    ("Condor Public License v1.1", "Condor-1.1", true, false, false),
    ("copyleft-next 0.3.0", "copyleft-next-0.3.0", false, false, false),
    ("copyleft-next 0.3.1", "copyleft-next-0.3.1", false, false, false),
    ("Common Public Attribution License 1.0", "CPAL-1.0", true, true, false),
    ("Common Public License 1.0", "CPL-1.0", true, true, false),
    ("Code Project Open License 1.02", "CPOL-1.02", false, false, false),
    ("Crossword License", "Crossword", false, false, false),
    ("CrystalStacker License", "CrystalStacker", false, false, false),
    ("CUA Office Public License v1.0", "CUA-OPL-1.0", false, true, false),
    ("Cube License", "Cube", false, false, false),
    ("curl License", "curl", false, false, false),
    ("Deutsche Freie Software Lizenz", "D-FSL-1.0", false, false, false),
    ("diffmark license", "diffmark", false, false, false),
    ("Data licence Germany – attribution – version 2.0", "DL-DE-BY-2.0", false, false, false),
    ("DOC License", "DOC", false, false, false),
    ("Dotseqn License", "Dotseqn", false, false, false),
    ("Detection Rule License 1.0", "DRL-1.0", false, false, false),
    ("DSDP License", "DSDP", false, false, false),
    ("dvipdfm License", "dvipdfm", false, false, false),
    ("Educational Community License v1.0", "ECL-1.0", false, true, false),
    ("Educational Community License v2.0", "ECL-2.0", true, true, false),
    ("Eiffel Forum License v1.0", "EFL-1.0", false, true, false),
    ("Eiffel Forum License v2.0", "EFL-2.0", true, true, false),
    ("eGenix.com Public License 1.1.0", "eGenix", false, false, false),
    ("Elastic License 2.0", "Elastic-2.0", false, false, false),
    ("Entessa Public License v1.0", "Entessa", false, true, false),
    ("EPICS Open License", "EPICS", false, false, false),
    ("Eclipse Public License 1.0", "EPL-1.0", true, true, false),
    ("Eclipse Public License 2.0", "EPL-2.0", true, true, false),
    ("Erlang Public License v1.1", "ErlPL-1.1", false, false, false),
    ("Etalab Open License 2.0", "etalab-2.0", false, false, false),
    ("EU DataGrid Software License", "EUDatagrid", true, true, false),
    ("European Union Public License 1.0", "EUPL-1.0", false, false, false),
    ("European Union Public License 1.1", "EUPL-1.1", true, true, false),
    ("European Union Public License 1.2", "EUPL-1.2", true, true, false),
    ("Eurosym License", "Eurosym", false, false, false),
    ("Fair License", "Fair", false, true, false),
    ("Fraunhofer FDK AAC Codec Library", "FDK-AAC", false, false, false),
    ("Frameworx Open License 1.0", "Frameworx-1.0", false, true, false),
    ("FreeBSD Documentation License", "FreeBSD-DOC", false, false, false),
    ("FreeImage Public License v1.0", "FreeImage", false, false, false),
    ("FSF All Permissive License", "FSFAP", true, false, false),
    ("FSF Unlimited License", "FSFUL", false, false, false),
    ("FSF Unlimited License (with License Retention)", "FSFULLR", false, false, false),
    ("FSF Unlimited License (With License Retention and Warranty Disclaimer)", "FSFULLRWD", false, false, false),
    ("Freetype Project License", "FTL", true, false, false),
    ("GD License", "GD", false, false, false),
    ("GNU Free Documentation License v1.1 only - invariants", "GFDL-1.1-invariants-only", false, false, false),
    ("GNU Free Documentation License v1.1 or later - invariants", "GFDL-1.1-invariants-or-later", false, false, false),
    ("GNU Free Documentation License v1.1 only - no invariants", "GFDL-1.1-no-invariants-only", false, false, false),
    ("GNU Free Documentation License v1.1 or later - no invariants", "GFDL-1.1-no-invariants-or-later", false, false, false),
    ("GNU Free Documentation License v1.1 only", "GFDL-1.1-only", true, false, false),
    ("GNU Free Documentation License v1.1 or later", "GFDL-1.1-or-later", true, false, false),
    ("GNU Free Documentation License v1.2 only - invariants", "GFDL-1.2-invariants-only", false, false, false),
    ("GNU Free Documentation License v1.2 or later - invariants", "GFDL-1.2-invariants-or-later", false, false, false),
    ("GNU Free Documentation License v1.2 only - no invariants", "GFDL-1.2-no-invariants-only", false, false, false),
    ("GNU Free Documentation License v1.2 or later - no invariants", "GFDL-1.2-no-invariants-or-later", false, false, false),
    ("GNU Free Documentation License v1.2 only", "GFDL-1.2-only", true, false, false),
    ("GNU Free Documentation License v1.2 or later", "GFDL-1.2-or-later", true, false, false),
    ("GNU Free Documentation License v1.3 only - invariants", "GFDL-1.3-invariants-only", false, false, false),
    ("GNU Free Documentation License v1.3 or later - invariants", "GFDL-1.3-invariants-or-later", false, false, false),
    ("GNU Free Documentation License v1.3 only - no invariants", "GFDL-1.3-no-invariants-only", false, false, false),
    ("GNU Free Documentation License v1.3 or later - no invariants", "GFDL-1.3-no-invariants-or-later", false, false, false),
    ("GNU Free Documentation License v1.3 only", "GFDL-1.3-only", true, false, false),
    ("GNU Free Documentation License v1.3 or later", "GFDL-1.3-or-later", true, false, false),
    ("Giftware License", "Giftware", false, false, false),
    ("GL2PS License", "GL2PS", false, false, false),
    ("3dfx Glide License", "Glide", false, false, false),
    ("Glulxe License", "Glulxe", false, false, false),
    ("Good Luck With That Public License", "GLWTPL", false, false, false),
    ("gnuplot License", "gnuplot", true, false, false),
    ("GNU General Public License v1.0 only", "GPL-1.0-only", false, false, false),
    ("GNU General Public License v1.0 or later", "GPL-1.0-or-later", false, false, false),
    ("GNU General Public License v2.0 only", "GPL-2.0-only", true, true, false),
    ("GNU General Public License v2.0 or later", "GPL-2.0-or-later", true, true, false),
    ("GNU General Public License v3.0 only", "GPL-3.0-only", true, true, false),
    ("GNU General Public License v3.0 or later", "GPL-3.0-or-later", true, true, false),
    ("gSOAP Public License v1.3b", "gSOAP-1.3b", false, false, false),
    ("Haskell Language Report License", "HaskellReport", false, false, false),
    ("Hippocratic License 2.1", "Hippocratic-2.1", false, false, false),
    ("Historical Permission Notice and Disclaimer", "HPND", true, true, false),
    ("Historical Permission Notice and Disclaimer - sell variant", "HPND-sell-variant", false, false, false),
    ("HTML Tidy License", "HTMLTIDY", false, false, false),
    ("IBM PowerPC Initialization and Boot Software", "IBM-pibs", false, false, false),
    ("ICU License", "ICU", false, false, false),
    ("Independent JPEG Group License", "IJG", true, false, false),
    ("ImageMagick License", "ImageMagick", false, false, false),
    ("iMatix Standard Function Library Agreement", "iMatix", true, false, false),
    ("Imlib2 License", "Imlib2", true, false, false),
    ("Info-ZIP License", "Info-ZIP", false, false, false),
    ("Intel Open Source License", "Intel", true, true, false),
    ("Intel ACPI Software License Agreement", "Intel-ACPI", false, false, false),
    ("Interbase Public License v1.0", "Interbase-1.0", false, false, false),
    ("IPA Font License", "IPA", true, true, false),
    ("IBM Public License v1.0", "IPL-1.0", true, true, false),
    ("ISC License", "ISC", true, true, false),
    ("Jam License", "Jam", false, true, false),
    ("JasPer License", "JasPer-2.0", false, false, false),
    ("Japan Network Information Center License", "JPNIC", false, false, false),
    ("JSON License", "JSON", false, false, false),
    ("Knuth CTAN License", "Knuth-CTAN", false, false, false),
    ("Licence Art Libre 1.2", "LAL-1.2", false, false, false),
    ("Licence Art Libre 1.3", "LAL-1.3", false, false, false),
    ("Latex2e License", "Latex2e", false, false, false),
    ("Leptonica License", "Leptonica", false, false, false),
    ("GNU Library General Public License v2 only", "LGPL-2.0-only", false, true, false),
    ("GNU Library General Public License v2 or later", "LGPL-2.0-or-later", false, true, false),
    ("GNU Lesser General Public License v2.1 only", "LGPL-2.1-only", true, true, false),
    ("GNU Lesser General Public License v2.1 or later", "LGPL-2.1-or-later", true, true, false),
    ("GNU Lesser General Public License v3.0 only", "LGPL-3.0-only", true, true, false),
    ("GNU Lesser General Public License v3.0 or later", "LGPL-3.0-or-later", true, true, false),
    ("Lesser General Public License For Linguistic Resources", "LGPLLR", false, false, false),
    ("libpng License", "Libpng", false, false, false),
    ("PNG Reference Library version 2", "libpng-2.0", false, false, false),
    ("libselinux public domain notice", "libselinux-1.0", false, false, false),
    ("libtiff License", "libtiff", false, false, false),
    ("libutil David Nugent License", "libutil-David-Nugent", false, false, false),
    ("Licence Libre du Québec - Permissive version 1.1", "LiLiQ-P-1.1", false, true, false),
    ("Licence Libre du Québec - Réciprocité version 1.1", "LiLiQ-R-1.1", false, true, false),
    ("Licence Libre du Québec - Réciprocité forte version 1.1", "LiLiQ-Rplus-1.1", false, true, false),
    ("Linux man-pages Copyleft", "Linux-man-pages-copyleft", false, false, false),
    ("Linux Kernel Variant of OpenIB.org license", "Linux-OpenIB", false, false, false),
    ("Lucent Public License Version 1.0", "LPL-1.0", false, true, false),
    ("Lucent Public License v1.02", "LPL-1.02", true, true, false),
    ("LaTeX Project Public License v1.0", "LPPL-1.0", false, false, false),
    ("LaTeX Project Public License v1.1", "LPPL-1.1", false, false, false),
    ("LaTeX Project Public License v1.2", "LPPL-1.2", true, false, false),
    ("LaTeX Project Public License v1.3a", "LPPL-1.3a", true, false, false),
    ("LaTeX Project Public License v1.3c", "LPPL-1.3c", false, true, false),
    ("LZMA SDK License (versions 9.11 to 9.20)", "LZMA-SDK-9.11-to-9.20", false, false, false),
    ("LZMA SDK License (versions 9.22 and beyond)", "LZMA-SDK-9.22", false, false, false),
    ("MakeIndex License", "MakeIndex", false, false, false),
    ("Minpack License", "Minpack", false, false, false),
    ("The MirOS Licence", "MirOS", false, true, false),
    ("MIT License", "MIT", true, true, false),
    ("MIT No Attribution", "MIT-0", false, true, false),
    ("Enlightenment License (e16)", "MIT-advertising", false, false, false),
    ("CMU License", "MIT-CMU", false, false, false),
    ("enna License", "MIT-enna", false, false, false),
    ("feh License", "MIT-feh", false, false, false),
    ("MIT License Modern Variant", "MIT-Modern-Variant", false, true, false),
    ("MIT Open Group variant", "MIT-open-group", false, false, false),
    ("MIT +no-false-attribs license", "MITNFA", false, false, false),
    ("Motosoto License", "Motosoto", false, true, false),
    ("mpi Permissive License", "mpi-permissive", false, false, false),
    ("mpich2 License", "mpich2", false, false, false),
    ("Mozilla Public License 1.0", "MPL-1.0", false, true, false),
    ("Mozilla Public License 1.1", "MPL-1.1", true, true, false),
    ("Mozilla Public License 2.0", "MPL-2.0", true, true, false),
    ("Mozilla Public License 2.0 (no copyleft exception)", "MPL-2.0-no-copyleft-exception", false, true, false),
    ("mplus Font License", "mplus", false, false, false),
    ("Microsoft Limited Public License", "MS-LPL", false, false, false),
    ("Microsoft Public License", "MS-PL", true, true, false),
    ("Microsoft Reciprocal License", "MS-RL", true, true, false),
    ("Matrix Template Library License", "MTLL", false, false, false),
    ("Mulan Permissive Software License, Version 1", "MulanPSL-1.0", false, false, false),
    ("Mulan Permissive Software License, Version 2", "MulanPSL-2.0", false, true, false),
    ("Multics License", "Multics", false, true, false),
    ("Mup License", "Mup", false, false, false),
    ("Nara Institute of Science and Technology License (2003)", "NAIST-2003", false, false, false),
    ("NASA Open Source Agreement 1.3", "NASA-1.3", false, true, false),
    ("Naumen Public License", "Naumen", false, true, false),
    ("Net Boolean Public License v1", "NBPL-1.0", false, false, false),
    ("Non-Commercial Government Licence", "NCGL-UK-2.0", false, false, false),
    ("University of Illinois/NCSA Open Source License", "NCSA", true, true, false),
    ("Net-SNMP License", "Net-SNMP", false, false, false),
    ("NetCDF license", "NetCDF", false, false, false),
    ("Newsletr License", "Newsletr", false, false, false),
    ("Nethack General Public License", "NGPL", false, true, false),
    ("NICTA Public Software License, Version 1.0", "NICTA-1.0", false, false, false),
    ("NIST Public Domain Notice", "NIST-PD", false, false, false),
    ("NIST Public Domain Notice with license fallback", "NIST-PD-fallback", false, false, false),
    ("Norwegian Licence for Open Government Data (NLOD) 1.0", "NLOD-1.0", false, false, false),
    ("Norwegian Licence for Open Government Data (NLOD) 2.0", "NLOD-2.0", false, false, false),
    ("No Limit Public License", "NLPL", false, false, false),
    ("Nokia Open Source License", "Nokia", true, true, false),
    ("Netizen Open Source License", "NOSL", true, false, false),
    ("Noweb License", "Noweb", false, false, false),
    ("Netscape Public License v1.0", "NPL-1.0", true, false, false),
    ("Netscape Public License v1.1", "NPL-1.1", true, false, false),
    ("Non-Profit Open Software License 3.0", "NPOSL-3.0", false, true, false),
    ("NRL License", "NRL", false, false, false),
    ("NTP License", "NTP", false, true, false),
    ("NTP No Attribution", "NTP-0", false, false, false),
    ("Open Use of Data Agreement v1.0", "O-UDA-1.0", false, false, false),
    ("Open CASCADE Technology Public License", "OCCT-PL", false, false, false),
    ("OCLC Research Public License 2.0", "OCLC-2.0", false, true, false),
    ("Open Data Commons Open Database License v1.0", "ODbL-1.0", true, false, false),
    ("Open Data Commons Attribution License v1.0", "ODC-By-1.0", false, false, false),
    ("SIL Open Font License 1.0", "OFL-1.0", true, false, false),
    ("SIL Open Font License 1.0 with no Reserved Font Name", "OFL-1.0-no-RFN", false, false, false),
    ("SIL Open Font License 1.0 with Reserved Font Name", "OFL-1.0-RFN", false, false, false),
    ("SIL Open Font License 1.1", "OFL-1.1", true, true, false),
    ("SIL Open Font License 1.1 with no Reserved Font Name", "OFL-1.1-no-RFN", false, true, false),
    ("SIL Open Font License 1.1 with Reserved Font Name", "OFL-1.1-RFN", false, true, false),
    ("OGC Software License, Version 1.0", "OGC-1.0", false, false, false),
    ("Taiwan Open Government Data License, version 1.0", "OGDL-Taiwan-1.0", false, false, false),
    ("Open Government Licence - Canada", "OGL-Canada-2.0", false, false, false),
    ("Open Government Licence v1.0", "OGL-UK-1.0", false, false, false),
    ("Open Government Licence v2.0", "OGL-UK-2.0", false, false, false),
    ("Open Government Licence v3.0", "OGL-UK-3.0", false, false, false),
    ("Open Group Test Suite License", "OGTSL", false, true, false),
    ("Open LDAP Public License v1.1", "OLDAP-1.1", false, false, false),
    ("Open LDAP Public License v1.2", "OLDAP-1.2", false, false, false),
    ("Open LDAP Public License v1.3", "OLDAP-1.3", false, false, false),
    ("Open LDAP Public License v1.4", "OLDAP-1.4", false, false, false),
    ("Open LDAP Public License v2.0 (or possibly 2.0A and 2.0B)", "OLDAP-2.0", false, false, false),
    ("Open LDAP Public License v2.0.1", "OLDAP-2.0.1", false, false, false),
    ("Open LDAP Public License v2.1", "OLDAP-2.1", false, false, false),
    ("Open LDAP Public License v2.2", "OLDAP-2.2", false, false, false),
    ("Open LDAP Public License v2.2.1", "OLDAP-2.2.1", false, false, false),
    ("Open LDAP Public License 2.2.2", "OLDAP-2.2.2", false, false, false),
    ("Open LDAP Public License v2.3", "OLDAP-2.3", true, false, false),
    ("Open LDAP Public License v2.4", "OLDAP-2.4", false, false, false),
    ("Open LDAP Public License v2.5", "OLDAP-2.5", false, false, false),
    ("Open LDAP Public License v2.6", "OLDAP-2.6", false, false, false),
    ("Open LDAP Public License v2.7", "OLDAP-2.7", true, false, false),
    ("Open LDAP Public License v2.8", "OLDAP-2.8", false, true, false),
    ("Open Market License", "OML", false, false, false),
    ("OpenSSL License", "OpenSSL", true, false, false),
    ("Open Public License v1.0", "OPL-1.0", false, false, false),
    ("Open Publication License v1.0", "OPUBL-1.0", false, false, false),
    ("OSET Public License version 2.1", "OSET-PL-2.1", false, true, false),
    ("Open Software License 1.0", "OSL-1.0", true, true, false),
    ("Open Software License 1.1", "OSL-1.1", true, false, false),
    ("Open Software License 2.0", "OSL-2.0", true, true, false),
    ("Open Software License 2.1", "OSL-2.1", true, true, false),
    ("Open Software License 3.0", "OSL-3.0", true, true, false),
    ("The Parity Public License 6.0.0", "Parity-6.0.0", false, false, false),
    ("The Parity Public License 7.0.0", "Parity-7.0.0", false, false, false),
    ("Open Data Commons Public Domain Dedication & License 1.0", "PDDL-1.0", false, false, false),
    ("PHP License v3.0", "PHP-3.0", false, true, false),
    ("PHP License v3.01", "PHP-3.01", true, true, false),
    ("Plexus Classworlds License", "Plexus", false, false, false),
    ("PolyForm Noncommercial License 1.0.0", "PolyForm-Noncommercial-1.0.0", false, false, false),
    ("PolyForm Small Business License 1.0.0", "PolyForm-Small-Business-1.0.0", false, false, false),
    ("PostgreSQL License", "PostgreSQL", false, true, false),
    ("Python Software Foundation License 2.0", "PSF-2.0", false, false, false),
    ("psfrag License", "psfrag", false, false, false),
    ("psutils License", "psutils", false, false, false),
    ("Python License 2.0", "Python-2.0", true, true, false),
    ("Python License 2.0.1", "Python-2.0.1", false, false, false),
    ("Qhull License", "Qhull", false, false, false),
    ("Q Public License 1.0", "QPL-1.0", true, true, false),
    ("Rdisc License", "Rdisc", false, false, false),
    ("Red Hat eCos Public License v1.1", "RHeCos-1.1", false, false, false),
    ("Reciprocal Public License 1.1", "RPL-1.1", false, true, false),
    ("Reciprocal Public License 1.5", "RPL-1.5", false, true, false),
    ("RealNetworks Public Source License v1.0", "RPSL-1.0", true, true, false),
    ("RSA Message-Digest License", "RSA-MD", false, false, false),
    ("Ricoh Source Code Public License", "RSCPL", false, true, false),
    ("Ruby License", "Ruby", true, false, false),
    ("Sax Public Domain Notice", "SAX-PD", false, false, false),
    ("Saxpath License", "Saxpath", false, false, false),
    ("SCEA Shared Source License", "SCEA", false, false, false),
    ("Scheme Language Report License", "SchemeReport", false, false, false),
    ("Sendmail License", "Sendmail", false, false, false),
    ("Sendmail License 8.23", "Sendmail-8.23", false, false, false),
    ("SGI Free Software License B v1.0", "SGI-B-1.0", false, false, false),
    ("SGI Free Software License B v1.1", "SGI-B-1.1", false, false, false),
    ("SGI Free Software License B v2.0", "SGI-B-2.0", true, false, false),
    ("Solderpad Hardware License v0.5", "SHL-0.5", false, false, false),
    ("Solderpad Hardware License, Version 0.51", "SHL-0.51", false, false, false),
    ("Simple Public License 2.0", "SimPL-2.0", false, true, false),
    ("Sun Industry Standards Source License v1.1", "SISSL", true, true, false),
    ("Sun Industry Standards Source License v1.2", "SISSL-1.2", false, false, false),
    ("Sleepycat License", "Sleepycat", true, true, false),
    ("Standard ML of New Jersey License", "SMLNJ", true, false, false),
    ("Secure Messaging Protocol Public License", "SMPPL", false, false, false),
    ("SNIA Public License 1.1", "SNIA", false, false, false),
    ("Spencer License 86", "Spencer-86", false, false, false),
    ("Spencer License 94", "Spencer-94", false, false, false),
    ("Spencer License 99", "Spencer-99", false, false, false),
    ("Sun Public License v1.0", "SPL-1.0", true, true, false),
    ("SSH OpenSSH license", "SSH-OpenSSH", false, false, false),
    ("SSH short notice", "SSH-short", false, false, false),
    ("Server Side Public License, v 1", "SSPL-1.0", false, false, false),
    ("SugarCRM Public License v1.1.3", "SugarCRM-1.1.3", false, false, false),
    ("Scheme Widget Library (SWL) Software License Agreement", "SWL", false, false, false),
    ("TAPR Open Hardware License v1.0", "TAPR-OHL-1.0", false, false, false),
    ("TCL/TK License", "TCL", false, false, false),
    ("TCP Wrappers License", "TCP-wrappers", false, false, false),
    ("TMate Open Source License", "TMate", false, false, false),
    ("TORQUE v2.5+ Software License v1.1", "TORQUE-1.1", false, false, false),
    ("Trusster Open Source License", "TOSL", false, false, false),
    ("Technische Universitaet Berlin License 1.0", "TU-Berlin-1.0", false, false, false),
    ("Technische Universitaet Berlin License 2.0", "TU-Berlin-2.0", false, false, false),
    ("Upstream Compatibility License v1.0", "UCL-1.0", false, true, false),
    ("Unicode License Agreement - Data Files and Software (2015)", "Unicode-DFS-2015", false, false, false),
    ("Unicode License Agreement - Data Files and Software (2016)", "Unicode-DFS-2016", false, true, false),
    ("Unicode Terms of Use", "Unicode-TOU", false, false, false),
    ("The Unlicense", "Unlicense", true, true, false),
    ("Universal Permissive License v1.0", "UPL-1.0", true, true, false),
    ("Vim License", "Vim", true, false, false),
    ("VOSTROM Public License for Open Source", "VOSTROM", false, false, false),
    ("Vovida Software License v1.0", "VSL-1.0", false, true, false),
    ("W3C Software Notice and License (2002-12-31)", "W3C", true, true, false),
    ("W3C Software Notice and License (1998-07-20)", "W3C-19980720", false, false, false),
    ("W3C Software Notice and Document License (2015-05-13)", "W3C-20150513", false, false, false),
    ("Sybase Open Watcom Public License 1.0", "Watcom-1.0", false, true, false),
    ("Wsuipa License", "Wsuipa", false, false, false),
    ("Do What The F*ck You Want To Public License", "WTFPL", true, false, false),
    ("X11 License", "X11", true, false, false),
    ("X11 License Distribution Modification Variant", "X11-distribute-modifications-variant", false, false, false),
    ("Xerox License", "Xerox", false, false, false),
    ("XFree86 License 1.1", "XFree86-1.1", true, false, false),
    ("xinetd License", "xinetd", true, false, false),
    ("X.Net License", "Xnet", false, true, false),
    ("XPP License", "xpp", false, false, false),
    ("XSkat License", "XSkat", false, false, false),
    ("Yahoo! Public License v1.0", "YPL-1.0", false, false, false),
    ("Yahoo! Public License v1.1", "YPL-1.1", true, false, false),
    ("Zed License", "Zed", false, false, false),
    ("Zend License v2.0", "Zend-2.0", true, false, false),
    ("Zimbra Public License v1.3", "Zimbra-1.3", true, false, false),
    ("Zimbra Public License v1.4", "Zimbra-1.4", false, false, false),
    ("zlib License", "Zlib", true, true, false),
    ("zlib/libpng License with Acknowledgement", "zlib-acknowledgement", false, false, false),
    ("Zope Public License 1.1", "ZPL-1.1", false, false, false),
    ("Zope Public License 2.0", "ZPL-2.0", true, true, false),
    ("Zope Public License 2.1", "ZPL-2.1", true, true, false),
    ("Affero General Public License v1.0", "AGPL-1.0", false, false, true),
    ("GNU Affero General Public License v3.0", "AGPL-3.0", false, false, true),
    ("BSD 2-Clause FreeBSD License", "BSD-2-Clause-FreeBSD", false, false, true),
    ("BSD 2-Clause NetBSD License", "BSD-2-Clause-NetBSD", false, false, true),
    ("bzip2 and libbzip2 License v1.0.5", "bzip2-1.0.5", false, false, true),
    ("eCos license version 2.0", "eCos-2.0", false, false, true),
    ("GNU Free Documentation License v1.1", "GFDL-1.1", false, false, true),
    ("GNU Free Documentation License v1.2", "GFDL-1.2", false, false, true),
    ("GNU Free Documentation License v1.3", "GFDL-1.3", false, false, true),
    ("GNU General Public License v1.0 only", "GPL-1.0", false, false, true),
    ("GNU General Public License v1.0 or later", "GPL-1.0+", false, false, true),
    ("GNU General Public License v2.0 only", "GPL-2.0", true, true, true),
    ("GNU General Public License v2.0 or later", "GPL-2.0+", true, true, true),
    ("GNU General Public License v2.0 w/Autoconf exception", "GPL-2.0-with-autoconf-exception", false, false, true),
    ("GNU General Public License v2.0 w/Bison exception", "GPL-2.0-with-bison-exception", false, false, true),
    ("GNU General Public License v2.0 w/Classpath exception", "GPL-2.0-with-classpath-exception", false, false, true),
    ("GNU General Public License v2.0 w/Font exception", "GPL-2.0-with-font-exception", false, false, true),
    ("GNU General Public License v2.0 w/GCC Runtime Library exception", "GPL-2.0-with-GCC-exception", false, false, true),
    ("GNU General Public License v3.0 only", "GPL-3.0", true, true, true),
    ("GNU General Public License v3.0 or later", "GPL-3.0+", true, true, true),
    ("GNU General Public License v3.0 w/Autoconf exception", "GPL-3.0-with-autoconf-exception", false, false, true),
    ("GNU General Public License v3.0 w/GCC Runtime Library exception", "GPL-3.0-with-GCC-exception", false, false, true),
    ("GNU Library General Public License v2 only", "LGPL-2.0", false, true, true),
    ("GNU Library General Public License v2 or later", "LGPL-2.0+", false, true, true),
    ("GNU Lesser General Public License v2.1 only", "LGPL-2.1", true, true, true),
    ("GNU Library General Public License v2.1 or later", "LGPL-2.1+", false, false, true),
    ("GNU Lesser General Public License v3.0 only", "LGPL-3.0", true, true, true),
    ("GNU Lesser General Public License v3.0 or later", "LGPL-3.0+", true, true, true),
    ("Nunit License", "Nunit", false, false, true),
    ("Standard ML of New Jersey License", "StandardML-NJ", true, false, true),
    ("wxWindows Library License", "wxWindows", false, false, true)
  ]
  var tbl: Table[string, LicenseData]
  for license in Licenses:
    tbl[license.id] = license
  tbl

proc newLicense*(id: string): License =
  result.id = id

proc findSpdxInfo(license: License): LicenseData =
  spdxTbl.getOrDefault license.id, ("Unknown", license.id, false, false, false)

proc `name`*(license: License): string =
  ## Get the full name of the license. If the license ID is not a valid SPDX
  ## identifier, "Unknown" is returned.
  runnableExamples:
    let
      mozilla = newLicense("MPL-2.0")
      proprietary = newLicense("Megacorp-Proprietary")

    assert mozilla.name == "Mozilla Public License 2.0"
    assert proprietary.name == "Unknown"
  ##
  findSpdxInfo(license).name

proc `isSpdx`*(license: License): bool =
  ## Returns `true` if the license ID is a valid SPDX identifier.
  spdxTbl.hasKey license.id

proc `isFsfLibre`*(license: License): bool =
  ## Returns `true` if the license is an approved FSF Free/Libre license, or
  ## `false` otherwise. If the license ID is not a valid SPDX identifier,
  ## `false` is returned.
  runnableExamples:
    let
      bsd0 = newLicense("0BSD")
      mozilla = newLicense("MPL-2.0")
      proprietary = newLicense("Megacorp-Proprietary")

    assert bsd0.isFsfLibre == false
    assert mozilla.isFsfLibre == true
    assert proprietary.isFsfLibre == false
  ##
  findSpdxInfo(license).isFsfLibre

proc `isOsiApproved`*(license: License): bool =
  ## Returns `true` if the license is an OSI-approved license, or
  ## `false` otherwise. If the license ID is not a valid SPDX identifier,
  ## `false` is returned.
  runnableExamples:
    let
      bsd0 = newLicense("0BSD")
      mozilla = newLicense("MPL-2.0")
      proprietary = newLicense("Megacorp-Proprietary")

    assert bsd0.isOsiApproved == true
    assert mozilla.isOsiApproved == true
    assert proprietary.isOsiApproved == false
  ##
  findSpdxInfo(license).isOsiApproved

proc `isDeprecated`*(license: License): bool =
  ## Returns `true` if the license ID is deprecated, or `false` if it is
  ## up-to-date. If the license ID is not a valid SPDX identifier,
  ## `false` is returned.
  runnableExamples:
    let
      gpl3 = newLicense("GPL-3.0")
      mozilla = newLicense("MPL-2.0")
      proprietary = newLicense("Megacorp-Proprietary")

    assert gpl3.isDeprecated == true
    assert mozilla.isDeprecated == false
    assert proprietary.isDeprecated == false
  ##
  findSpdxInfo(license).isDeprecated
